Style the leaderboard game
Ridwanullahi-code/Leaderboard pull request #4
Opened 2022-10-20 19:22 UTC by Ridwanullahi-code

- Add customized background to refresh and submit buttons
- Styling the button states.

2022-10-20 20:33 UTC, codecaiine requested changes
Hi @Ridwanullahi-code , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Good project implementation :heavy_check_mark: 
- No linters errors :heavy_check_mark: 
- Good design :heavy_check_mark: 

## Required Changes ♻️
- [ ] Please make sure to add a license in your repo root, just create a new license file and copy this [MIT](https://choosealicense.com/licenses/mit/) license and customize it by adding your name to make your readme more professional :smile: 
- [ ] Please add a link to your repo issue in your readme in case someone want to contribute to your project in order to make your readme more professional :heavy_check_mark: 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-20 20:33 UTC, codecaiine commented on css/index.css
> +}
- [ ] Good job with your design but please make sure that your design layout looks like the leaderboard [wireframe](https://github.com/microverseinc/curriculum-javascript/blob/main/leaderboard/images/leaderboard_wireframe.png) as required for this project as a developer you need to pay attention to details :+1: 

#### Your design
![Screenshot from 2022-10-20 20-20-03](https://user-images.githubusercontent.com/6615394/197050786-62fbf356-0f66-4790-8a98-16eec7da71cd.jpg)

#### Wireframe
![Screenshot from 2022-10-20 20-25-10](https://user-images.githubusercontent.com/6615394/197050975-1d2dfb20-d75a-4ee8-b06c-4be055cb980c.png)

2022-10-21 11:48 UTC, fobadara requested changes
Hi @Ridwanullahi-code, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
👍🏽 Linters are passing

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- You don't need to add. `feature/` before the feature branch's name.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-21 11:48 UTC, fobadara commented on dist/index.html
>                  <input type="button" name="submit" class="submit-btn" value="submit">
[Required] Kindly ensure that the submit button is aligned to the right. As the previous reviewer suggested you should ensure that your design matches the template.

2022-10-21 11:48 UTC, fobadara commented on README.md
- Your license does not include your details like fullname.

2022-10-21 17:18 UTC, Deepakdanger approved these changes
Hi @Ridwanullahi-code,
### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-22 08:12 UTC, merged